config/routes.rb
      put '/dados_demograficos' => 'execucao#salvar_dados_demograficos', :as => :execucao_salvar_dados_demograficos
      get '/dados_demograficos' => 'execucao#dados_demograficos', :as => :execucao_dados_demograficos
      scope "/exame_fisico" do
        put '/exame_forca' => 'execucao#salvar_avaliacao_clinica', :as => :execucao_salvar_exame_forca
        get '/exame_forca' => 'execucao#avaliacao_clinica', :as => :execucao_exame_forca
        put '/reflexos' => 'execucao#salvar_avaliacao_clinica', :as => :execucao_salvar_reflexos
        get '/reflexos' => 'execucao#avaliacao_clinica', :as => :execucao_reflexos
        put '/esfincteres' => 'execucao#salvar_avaliacao_clinica', :as => :execucao_salvar_esfincteres
        get '/esfincteres' => 'execucao#avaliacao_clinica', :as => :execucao_esfincteres
        put '/coordenacao' => 'execucao#salvar_avaliacao_clinica', :as => :execucao_salvar_coordenacao
        get '/coordenacao' => 'execucao#avaliacao_clinica', :as => :execucao_coordenacao
        put '/tonus_muscular' => 'execucao#salvar_avaliacao_clinica', :as => :execucao_salvar_tonus_muscular
        get '/tonus_muscular' => 'execucao#avaliacao_clinica', :as => :execucao_tonus_muscular
        put '/nervos_perifericos' => 'execucao#salvar_avaliacao_clinica', :as => :execucao_salvar_nervos_perifericos
        get '/nervos_perifericos' => 'execucao#avaliacao_clinica', :as => :execucao_nervos_perifericos
      end
    end
    scope "/exames" do
      get '/teste_gravidez' => 'execucao#new_laudo', :as => :execucao_teste_gravidez
      post '/teste_gravidez' => 'execucao#create_laudo', :as => :execucao_salvar_teste_gravidez
      get '/hemograma' => 'execucao#new_laudo', :as => :execucao_hemograma
      post '/hemograma' => 'execucao#create_laudo', :as => :execucao_salvar_hemograma
      get '/func_renal' => 'execucao#new_laudo', :as => :execucao_func_renal
      post '/func_renal' => 'execucao#create_laudo', :as => :execucao_salvar_func_renal
      get '/func_hepatica' => 'execucao#new_laudo', :as => :execucao_func_hepatica
      post '/func_hepatica' => 'execucao#create_laudo', :as => :execucao_salvar_func_hepatica
      get '/rx_torax' => 'execucao#new_laudo', :as => :execucao_rx_torax
      post '/rx_torax' => 'execucao#create_laudo', :as => :execucao_salvar_rx_torax
    end
  end
  
  scope "/alocacao" do
    get '/incluir' => 'alocacao#incluir'
    post '/incluir' => 'alocacao#salvar_incluir', :as => :salvar_incluir
    get '/excluir' => 'alocacao#incluir'
    post '/excluir' => 'alocacao#salvar_incluir', :as => :salvar_incluir
    get '/analisar_prontuarios' => 'alocacao#analisar_prontuarios'
    get '/randomizar' => 'alocacao#randomizar'
    get '/dispensacao' => 'alocacao#dispensacao', :as => :alocacao_dispensacao
    put '/dispensacao' => 'alocacao#salvar_dispensacao', :as => :alocacao_salvar_dispensacao
    scope "/analisar_prontuarios" do
      get '/avaliacao_clinica' => 'alocacao#show_avaliacao_clinica', :as => :show_avaliacao_clinica
      get '/criterios' => 'alocacao#show_criterios', :as => :show_criterios
      get '/biopsia' => 'alocacao#show_biopsia', :as => :show_biopsia
      get '/neurofisiologia' => 'alocacao#analisar_prontuarios', :as => :show_neurofisiologia
      get '/enmg' => 'alocacao#show_enmg', :as => :show_enmg
      get '/cheps' => 'alocacao#show_cheps', :as => :show_cheps
      get '/qst' => 'alocacao#show_qst', :as => :show_qst
      get '/questionarios' => 'alocacao#analisar_prontuarios', :as => :show_questionarios
      get '/eva' => 'alocacao#show_eva', :as => :show_eva
      get '/dn4' => 'alocacao#show_dn4', :as => :show_dn4
      get '/lanss' => 'alocacao#show_lanss', :as => :show_lanss
      get '/sf36' => 'alocacao#show_sf36', :as => :show_sf36
      get '/mini_mental' => 'alocacao#show_mini_mental', :as => :show_mini_mental
      get '/exames' => 'alocacao#analisar_prontuarios', :as => :show_exames
      get '/gravidez' => 'alocacao#show_gravidez', :as => :show_gravidez
      get '/hemograma' => 'alocacao#show_hemograma', :as => :show_hemograma
      get '/func_renal' => 'alocacao#show_func_renal', :as => :show_func_renal
      get '/func_hepatica' => 'alocacao#show_func_hepatica', :as => :show_func_hepatica
      get '/urinocultura' => 'alocacao#show_urinocultura', :as => :show_urinocultura
    end
    scope "/randomizar" do
      get '/criterios' => 'alocacao#criterios', :as => :alocacao_criterios
      put '/criterios' => 'alocacao#salvar_criterios', :as => :alocacao_salvar_criterios
      get '/grupos' => 'alocacao#grupos', :as => :alocacao_grupos
      put '/grupos' => 'alocacao#salvar_grupos', :as => :alocacao_salvar_grupos
      get '/avaliacao_clinica' => 'alocacao#new_avaliacao_clinica', :as => :alocacao_new_avaliacao_clinica
      scope "/avaliacao_clinica" do
        put '/exame_fisico' => 'alocacao#salvar_avaliacao_clinica', :as => :alocacao_salvar_exame_fisico
        get '/exame_fisico' => 'alocacao#avaliacao_clinica', :as => :alocacao_exame_fisico
        put '/anamnese' => 'alocacao#salvar_avaliacao_clinica', :as => :alocacao_salvar_anamnese
        get '/anamnese' => 'alocacao#avaliacao_clinica', :as => :alocacao_anamnese
        put '/sinais_vitais' => 'alocacao#salvar_avaliacao_clinica', :as => :alocacao_salvar_sinais_vitais
        get '/sinais_vitais' => 'alocacao#avaliacao_clinica', :as => :alocacao_sinais_vitais
        put '/dados_demograficos' => 'alocacao#salvar_dados_demograficos', :as => :alocacao_salvar_dados_demograficos
        get '/dados_demograficos' => 'alocacao#dados_demograficos', :as => :alocacao_dados_demograficos
        scope "/exame_fisico" do
          put '/exame_forca' => 'alocacao#salvar_avaliacao_clinica', :as => :alocacao_salvar_exame_forca
          get '/exame_forca' => 'alocacao#avaliacao_clinica', :as => :alocacao_exame_forca
          put '/reflexos' => 'alocacao#salvar_avaliacao_clinica', :as => :alocacao_salvar_reflexos
          get '/reflexos' => 'alocacao#avaliacao_clinica', :as => :alocacao_reflexos
          put '/esfincteres' => 'alocacao#salvar_avaliacao_clinica', :as => :alocacao_salvar_esfincteres
          get '/esfincteres' => 'alocacao#avaliacao_clinica', :as => :alocacao_esfincteres
          put '/coordenacao' => 'alocacao#salvar_avaliacao_clinica', :as => :alocacao_salvar_coordenacao
          get '/coordenacao' => 'alocacao#avaliacao_clinica', :as => :alocacao_coordenacao
          put '/tonus_muscular' => 'alocacao#salvar_avaliacao_clinica', :as => :alocacao_salvar_tonus_muscular
          get '/tonus_muscular' => 'alocacao#avaliacao_clinica', :as => :alocacao_tonus_muscular
          put '/nervos_perifericos' => 'alocacao#salvar_avaliacao_clinica', :as => :alocacao_salvar_nervos_perifericos
          get '/nervos_perifericos' => 'alocacao#avaliacao_clinica', :as => :alocacao_nervos_perifericos
        end
      end
    end
  end
  
  scope "/eventos_adversos" do
    get '/evento_adverso_grave' => 'eventos_adversos#evento_adverso_grave', :as => :evento_adverso_grave
    post '/evento_adverso_grave' => 'eventos_adversos#salvar_evento_adverso_grave', :as => :salvar_evento_adverso_grave
    get '/superdose' => 'eventos_adversos#superdose', :as => :superdose
    post '/superdose' => 'eventos_adversos#salvar_superdose', :as => :salvar_superdose
    get '/gravidez' => 'eventos_adversos#gravidez', :as => :gravidez
    post '/gravidez' => 'eventos_adversos#salvar_gravidez', :as => :salvar_gravidez
    get '/new' => 'eventos_adversos#evento_adverso', :as => :evento_adverso
    post '/new' => 'eventos_adversos#salvar_evento_adverso', :as => :salvar_evento_adverso
    get '/show_evento_adverso_grave/:id' => 'eventos_adversos#show_evento_adverso_grave', :as => :show_evento_adverso_grave
  end
  
  scope "/selecao" do
    get '/exames' => 'selecao#exames', :as => :selecao_exames
    get '/questionarios' => 'selecao#questionarios', :as => :selecao_questionarios
    get '/neurofisiologia' => 'selecao#neurofisiologia', :as => :selecao_neurofisiologia
    get '/biopsia/new' => 'selecao#new_laudo', :as => :selecao_new_biopsia
    post '/biopsia/new' => 'selecao#create_laudo', :as => :selecao_biopsia
    get '/criterios/new' => 'selecao#new_criterio', :as => :selecao_new_criterio
    post '/criterios/new' => 'selecao#create_criterio', :as => :selecao_criterios
    get '/tcle/new' => 'selecao#new_laudo', :as => :selecao_new_tcle
    post '/tcle/new' => 'selecao#create_laudo', :as => :selecao_tcles
    scope "/avaliacao_clinica" do
      put '/exame_fisico' => 'selecao#salvar_avaliacao_clinica', :as => :selecao_salvar_exame_fisico
      get '/exame_fisico' => 'selecao#avaliacao_clinica', :as => :selecao_exame_fisico
      put '/anamnese' => 'selecao#salvar_avaliacao_clinica', :as => :selecao_salvar_anamnese
      get '/anamnese' => 'selecao#avaliacao_clinica', :as => :selecao_anamnese
      put '/sinais_vitais' => 'selecao#salvar_avaliacao_clinica', :as => :selecao_salvar_sinais_vitais
      get '/sinais_vitais' => 'selecao#avaliacao_clinica', :as => :selecao_sinais_vitais
      put '/dados_demograficos' => 'selecao#salvar_dados_demograficos', :as => :selecao_salvar_dados_demograficos
      get '/dados_demograficos' => 'selecao#dados_demograficos', :as => :selecao_dados_demograficos
      get '/new' => 'selecao#new_avaliacao_clinica', :as => :selecao_new_avaliacao_clinica
      scope "/exame_fisico" do
        put '/exame_forca' => 'selecao#salvar_avaliacao_clinica', :as => :selecao_salvar_exame_forca
        get '/exame_forca' => 'selecao#avaliacao_clinica', :as => :selecao_exame_forca
        put '/reflexos' => 'selecao#salvar_avaliacao_clinica', :as => :selecao_salvar_reflexos
        get '/reflexos' => 'selecao#avaliacao_clinica', :as => :selecao_reflexos
        put '/esfincteres' => 'selecao#salvar_avaliacao_clinica', :as => :selecao_salvar_esfincteres
        get '/esfincteres' => 'selecao#avaliacao_clinica', :as => :selecao_esfincteres

app/controllers/selecao_controller.rb
# encoding: utf-8
class SelecaoController < ApplicationController

  def new_laudo
    if !session[:voluntario].blank?
      @visita = Visita.find_or_create_by_voluntario_id_and_numero(session[:voluntario], 1)
    end
    @laudo = @visita ? @visita.laudos.build : Laudo.new
    params[:pagina] = request.fullpath
    respond_to do |format|
      format.html { render request.fullpath }
      format.xml  { render :xml => @laudo }
    end
  end
  
  def create_laudo
    @laudo = Laudo.new params[:laudo]
    respond_to do |format|
      if Voluntario.find(session[:voluntario]).visitas.find_by_numero(1).laudos.find_all_by_tipo(params[:laudo][:tipo]).size > 0
        flash.now[:error] = 'O laudo deste voluntário já foi registrado'
        format.html { render request.fullpath }
        format.xml  { render :xml => @laudo.errors, :status => :unprocessable_entity }
      else
        if @laudo.save
          format.html { redirect_to(selecao_menu_path, :notice => 'Laudo registrado com sucesso') }
          format.xml  { render :xml => @laudo, :status => :created }
        else
          format.html { render request.fullpath }
          format.xml  { render :xml => @laudo.errors, :status => :unprocessable_entity }
        end
      end
    end
  end
  
  def new_criterio
    if !session[:voluntario].blank?
      @voluntario = Voluntario.find session[:voluntario]
      @voluntario.criterios.build params[:criterio]
      @voluntario.inclusoes.build params[:inclusao]
    end
    params[:pagina] = request.fullpath

    respond_to do |format|
      format.html { render request.fullpath }
      format.xml  { render :xml => @voluntario }
    end
  end
  
  def create_criterio
    @voluntario = Voluntario.find session[:voluntario]
    @voluntario.criterios.build params[:voluntario][:criterios]
    @voluntario.inclusoes.build params[:voluntario][:inclusoes]

    respond_to do |format|
      if @voluntario.criterios.size > 2
        flash.now[:error] = 'Os critérios I/E deste voluntário já foram aplicados'
        format.html { render request.fullpath }
        format.xml  { render :xml => @voluntario.errors, :status => :unprocessable_entity }
      else
        salvou = false
        Criterio.transaction do
          if @voluntario.save
            salvou = true
          end
        end
        if salvou
          format.html { redirect_to(selecao_menu_path, :notice => 'Critérios I/E aplicados com sucesso') }
          format.xml  { render :xml => @voluntario, :status => :created }
        else
          format.html { render request.fullpath }
          format.xml  { render :xml => @voluntario.errors, :status => :unprocessable_entity }
        end
      end
    end
  end
  
  def new_avaliacao_clinica
    if !session[:voluntario].blank?
      visita = Visita.find_or_create_by_voluntario_id_and_numero(session[:voluntario], 1)
    end
    params[:pagina] = request.fullpath
    respond_to do |format|
      format.html { render request.fullpath }
    end
  end
  
  def dados_demograficos
    @voluntario = Voluntario.find session[:voluntario]
    respond_to do |format|
      format.html { render request.fullpath }
      format.xml  { render :xml => @voluntario }
    end
  end
  
  def salvar_dados_demograficos
    @voluntario = Voluntario.find session[:voluntario]
    @voluntario.atualiza_dados_demograficos
    
    respond_to do |format|
      if @voluntario.update_attributes(params[:voluntario])
        format.html { redirect_to(selecao_new_avaliacao_clinica_path, :notice => 'Dados demográficos atualizados com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render request.fullpath }
        format.xml  { render :xml => @voluntario.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def avaliacao_clinica
    @voluntario = Voluntario.find session[:voluntario]
    @avaliacao_clinica = AvaliacaoClinica.find_by_avaliavel_id_and_avaliavel_type(
        Visita.find_by_voluntario_id_and_numero(session[:voluntario], 1).id, 'Visita')
    unless @avaliacao_clinica
      @avaliacao_clinica = AvaliacaoClinica.
        new(:avaliavel_id => Visita.find_by_voluntario_id_and_numero(session[:voluntario], 1).id,
               :avaliavel_type => 'Visita', :usuario_id => session[:usuario])
      @avaliacao_clinica.build_exame_fisico
      @avaliacao_clinica.exame_fisico.build_exame_complemento
      @avaliacao_clinica.save(:validate => false)
    end
    respond_to do |format|
      format.html { render request.fullpath }
    end
  end
  
  def salvar_avaliacao_clinica
    @avaliacao_clinica = AvaliacaoClinica.find_by_avaliavel_id_and_avaliavel_type(
        Visita.find_by_voluntario_id_and_numero(session[:voluntario], 1).id, 'Visita')
    
    retorno = selecao_new_avaliacao_clinica_path
    if request.fullpath.include? 'sinais_vitais'
      notice = 'Sinais vitais salvos com sucesso.'
      @avaliacao_clinica.salva_sinais_vitais
    elsif request.fullpath.include? 'anamnese'
      notice = 'Anamnese salva com sucesso.'
      @avaliacao_clinica.salva_anamnese
    else
      notice = 'Exame físico salvo com sucesso.'
      if request.fullpath.include? 'fisico/'
        retorno = selecao_exame_fisico_path
      end
    end
    respond_to do |format|
      if @avaliacao_clinica.update_attributes(params[:avaliacao_clinica])
        format.html { redirect_to(retorno, :notice => notice) }
        format.xml  { head :ok }
      else
        format.html do
          flash.now[:error] = "Não foi possivel salvar essa avaliação."
          render request.fullpath
        end
        format.xml  { render :xml => @avaliacao_clinica.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def neurofisiologia
    render "dorneuro/selecao/neurofisiologia"
  end
  
  def questionarios
    render "dorneuro/selecao/questionarios"
  end
  
  def exames
    render "dorneuro/selecao/exames"
  end
  
end

app/views/dorneuro/selecao/questionarios/dn4.html.erb
<h1>Questionários - DN4</h1>

<% @laudo.build_dados_dn4 %>

<% if @laudo.errors.any? %>
  <div class="alert alert-dismissable alert-danger">
    <strong><%= pluralize(@laudo.errors.count, "erro impediu") %> o Questionário - DN4 de ser salvo:</strong>
    <ul>
    <% @laudo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'partials/escolher_voluntario', :usuario => false %>

<% unless session[:voluntario].blank? %>
  <%= form_for @laudo, :url => selecao_salvar_dn4_path, :html => { :multipart => true } do |f| %>
    <div class='control-group'>
      <%= f.fields_for :dados_dn4 do |d| %>
        <%= render 'partials/laudos/form_dn4', :f => d %>
      <% end %>
      
      <%= render 'partials/upload', :f => f, :imagem => :imagem, :texto => 'Anexar imagem do laudo do DN4',
        :texto_data => 'Data do questionário', :tipo => Laudo::TIPO_DN4 %>

      <%= f.label :escore, 'Escore total (máximo 10)', :class => 'control-label' %>
      <%= f.text_field :escore, {:readonly => true} %>
      
      <%= f.label :usuario_id, nil, :class => 'control-label' %>
      <%= f.select :usuario_id, options_from_collection_for_select(Usuario.all, 'id', 'nome') %>
      
      <%= hidden_field_tag 'laudo[visita_id]', Visita.find_by_voluntario_id_and_numero(session[:voluntario], 1).id %>
      <%= hidden_field_tag 'laudo[tipo]', Laudo::TIPO_DN4 %>
    </div>
    
    <div class='form-actions'>
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to 'Voltar', selecao_questionarios_path, :class => 'btn btn-danger' %>
    </div>
  <% end %>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
   $("#new_laudo").ketchup();
});

var escore = 0;

function atualiza_escore(el) {
 if ( $(el).is(':checked') ) {
   if ( $(el).val() == "true") {
    escore = escore + 1;
   }
   else {
     escore = escore - 1;
   }
   $('#laudo_escore').val(escore);
 }
}
</script>

app/views/dorneuro/selecao/questionarios/eva.html.erb
<h1>Questionários - EVA</h1>

<% if @laudo.errors.any? %>
  <div class="alert alert-dismissable alert-danger">
    <strong><%= pluralize(@laudo.errors.count, "erro impediu") %> o Questionário - EVA de ser salvo:</strong>
    <ul>
    <% @laudo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'partials/escolher_voluntario', :usuario => false %>

<% unless session[:voluntario].blank? %>
  <%= form_for @laudo, :url => selecao_salvar_eva_path, :html => { :multipart => true } do |f| %>
    <div class='control-group'>
      <%= render 'partials/upload', :f => f, :imagem => :imagem, :texto => 'Anexar imagem do laudo da EVA',
        :texto_data => 'Data do questionário', :tipo => Laudo::TIPO_EVA %>
    
      <%= f.label :escore, 'Nota de 0 a 10 na Escala Visual Analógica', :class => 'control-label' %>
      <%= f.text_field :escore, "data-validate" => "validate(required, range(0,10)) on(blur change)" %>
      
      <%= f.label :usuario_id, nil, :class => 'control-label' %>
      <%= f.select :usuario_id, options_from_collection_for_select(Usuario.all, 'id', 'nome') %>
      
      <%= hidden_field_tag 'laudo[visita_id]', Visita.find_by_voluntario_id_and_numero(session[:voluntario], 1).id %>
      <%= hidden_field_tag 'laudo[tipo]', Laudo::TIPO_EVA %>
    </div>
    
    <div class='form-actions'>
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to 'Voltar', selecao_questionarios_path, :class => 'btn btn-danger' %>
    </div>
  <% end %>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
   $("#new_laudo").ketchup();
});
</script>

app/views/dorneuro/selecao/questionarios/lanss.html.erb
<%= javascript_include_tag 'lanss' %>

<h1>Questionários - LANSS</h1>

<% @laudo.build_dados_lanss %>

<% if @laudo.errors.any? %>
  <div class="alert alert-dismissable alert-danger">
    <strong><%= pluralize(@laudo.errors.count, "erro impediu") %> o Questionário - LANSS de ser salvo:</strong>
    <ul>
    <% @laudo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'partials/escolher_voluntario', :usuario => false %>

<% unless session[:voluntario].blank? %>
  <%= form_for @laudo, :url => selecao_salvar_lanss_path, :html => { :multipart => true } do |f| %>
    <div class='control-group'>
      <%= f.fields_for :dados_lanss do |lanss| %>
        <%= render 'partials/laudos/form_lanss', :f => lanss %>
      <% end %>
      
      <%= render 'partials/upload', :f => f, :imagem => :imagem, :texto => 'Anexar imagem do laudo do LANSS',
        :texto_data => 'Data do questionário', :tipo => Laudo::TIPO_LANSS %>
    
      <%= f.label :escore, 'Escore total (máximo 24)', :class => 'control-label' %>
      <%= f.text_field :escore, {:readonly => true} %>
      
      <br/>
      
      <div class='radio inline'>
        <%= f.radio_button :bool, true %>
        <%= f.label :bool_true, 'Escore < 12: mecanismos neuropáticos são improváveis de estarem contribuindo para a dor do paciente' %>
      </div>
      
      <div class='clear'></div>
      
      <div class='radio inline'>
        <%= f.radio_button :bool, false %>
        <%= f.label :bool_false, "Escore ≥ 12: mecanismos neuropáticos provavelmente estão contribuindo para a dor do paciente" %>
      </div>
      
      <%= f.label :usuario_id, nil, :class => 'control-label' %>
      <%= f.select :usuario_id, options_from_collection_for_select(Usuario.all, 'id', 'nome') %>
      
      <%= hidden_field_tag 'laudo[visita_id]', Visita.find_by_voluntario_id_and_numero(session[:voluntario], 1).id %>
      <%= hidden_field_tag 'laudo[tipo]', Laudo::TIPO_LANSS %>
    </div>
    
    <div class='form-actions'>
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to 'Voltar', selecao_questionarios_path, :class => 'btn btn-danger' %>
    </div>
  <% end %>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
   $("#new_laudo").ketchup();
});
</script>

app/views/dorneuro/selecao/questionarios/mini_mental.html.erb
<h1>Questionários - Mini mental</h1>

<% if @laudo.errors.any? %>
  <div class="alert alert-dismissable alert-danger">
    <strong><%= pluralize(@laudo.errors.count, "erro impediu") %> o Questionário - Mini mental de ser salvo:</strong>
    <ul>
    <% @laudo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'partials/escolher_voluntario', :usuario => false %>

<% unless session[:voluntario].blank? %>
  <%= form_for @laudo, :url => selecao_salvar_mini_mental_path, :html => { :multipart => true } do |f| %>
    <div class='control-group'>
      <%= render 'partials/upload', :f => f, :imagem => :imagem, :texto => 'Anexar imagem do laudo do Mini mental', :texto_data => 'Data do questionário', :tipo => Laudo::TIPO_MINI_MENTAL %>
    
      <%= f.label :escore, 'Escore total', :class => 'control-label' %>
      <%= f.text_field :escore, "data-validate" => "validate(required, range(0,10)) on(blur change)" %>
      
      <%= f.label :usuario_id, nil, :class => 'control-label' %>
      <%= f.select :usuario_id, options_from_collection_for_select(Usuario.all, 'id', 'nome') %>
      
      <%= hidden_field_tag 'laudo[visita_id]', Visita.find_by_voluntario_id_and_numero(session[:voluntario], 1).id %>
      <%= hidden_field_tag 'laudo[tipo]', Laudo::TIPO_MINI_MENTAL %>
    </div>
    
    <div class='form-actions'>
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to 'Voltar', selecao_questionarios_path, :class => 'btn btn-danger' %>
    </div>
  <% end %>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
   $("#new_laudo").ketchup();
});
</script>

app/views/dorneuro/selecao/questionarios/sf36.html.erb
<h1>Questionários - SF36</h1>

<% @laudo.build_dados_sf36 %>

<% if @laudo.errors.any? %>
  <div class="alert alert-dismissable alert-danger">
    <strong><%= pluralize(@laudo.errors.count, "erro impediu") %> o Questionário - SF36 de ser salvo:</strong>
    <ul>
    <% @laudo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'partials/escolher_voluntario', :usuario => false %>

<% unless session[:voluntario].blank? %>
  <%= form_for @laudo, :url => selecao_salvar_sf36_path, :html => { :multipart => true } do |f| %>
    
    <%= f.fields_for :dados_sf36 do |dados| %>
      <%= render 'partials/laudos/form_sf36', :f => dados %>
    <% end %>
    
    <div class='control-group'>
      <%= render 'partials/upload', :f => f, :imagem => :imagem, :texto => 'Anexar imagem do laudo do SF36',
        :texto_data => 'Data do questionário', :tipo => Laudo::TIPO_SF36 %>
    
      <%= f.label :escore, 'Escore total', :class => 'control-label' %>
      <%= f.text_field :escore, {:readonly => true} %>
    
      <%= f.label :usuario_id, nil, :class => 'control-label' %>
      <%= f.select :usuario_id, options_from_collection_for_select(Usuario.all, 'id', 'nome') %>
      
      <%= hidden_field_tag 'laudo[visita_id]', Visita.find_by_voluntario_id_and_numero(session[:voluntario], 1).id %>
      <%= hidden_field_tag 'laudo[tipo]', Laudo::TIPO_SF36 %>
    </div>
    
    <div class='form-actions'>
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to 'Voltar', selecao_questionarios_path, :class => 'btn btn-danger' %>
    </div>
  <% end %>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
   $("#new_laudo").ketchup();
});
</script>